version: "3"

services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql
  
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ./www:/var/www
      - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "80:80"

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
